app_name: go_service

app_host: :8080
# 运行模式：debug,release
run_mode: debug

accounts: [{appid: 33efac4290daa8607cc5541c73b9a597, secret: 2c4518ae7270e7f5cd5b255a1f46e93b}]

#redis连接信息
redis_host: 127.0.0.1:6379
redis_pwd: 
redis_db: 0
redis_maxidle: 100
redis_maxactive: 200
redis_idletimeout: 30

#mysql连接信息 帐号：root 密码：123 主机：localhost 端口：3306 数据库：testdb
mysql_dsn: root:123@tcp(localhost:3306)/testdb?parseTime=true
mysql_maxidleconns: 100
mysql_maxopenconns: 100
